# handy aliases + color support 
if [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --group-directories-first --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# ls aliases
alias ll='ls --group-directories-first -l'
alias la='ls --group-directories-first -A'
alias l='ls --group-directories-first -CF'

if [ -f /usr/bin/colordiff ]; then
  alias diff='colordiff'
fi

# private aliases
alias gcc='gcc-4.6 -std=c99 -Wall'
alias g++='g++-4.6 -std=c++0x -Wall'
alias gfortran='gfortran-4.5 -std=f95'
alias emacs='emacs23 -nw'
alias python='python3.2'
alias clisp='clisp -i ${HOME}/lib/std.cl'
alias ghostscript='ghostscript -dSAFER'
alias gs='gs -dSAFER'
alias dir2ogv='dir2ogv.sh'

# aptitude aliases
alias sapt='aptitude search'
alias ssapt='apt-get source'
alias vapt='aptitude versions'
